"""adoption table

Revision ID: 2dad07f3639d
Revises: 7ae38684c28b
Create Date: 2024-01-13 16:00:45.127920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dad07f3639d'
down_revision = '7ae38684c28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('shelter', sa.String(length=100), nullable=False),
    sa.Column('animal', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.String(length=10), nullable=False),
    sa.Column('ocupation', sa.String(length=30), nullable=False),
    sa.Column('income', sa.String(length=20), nullable=False),
    sa.Column('experience', sa.String(length=10), nullable=False),
    sa.Column('story', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoption')
    # ### end Alembic commands ###
