"""email for shelter

Revision ID: 43d007a291b5
Revises: 4635f5e97cab
Create Date: 2024-01-13 18:06:48.538869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d007a291b5'
down_revision = '4635f5e97cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
