"""mica modificare la Animal.adopted

Revision ID: 4635f5e97cab
Revises: 2dad07f3639d
Create Date: 2024-01-13 16:26:19.398110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4635f5e97cab'
down_revision = '2dad07f3639d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('adopted',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('adopted',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
