"""Add Curiosity model

Revision ID: 733f135d6fd4
Revises: 43d007a291b5
Create Date: 2024-01-15 16:17:28.408631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733f135d6fd4'
down_revision = '43d007a291b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curiosity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curiosity')
    # ### end Alembic commands ###
