"""Added picture to facts

Revision ID: 82133fd39de9
Revises: 733f135d6fd4
Create Date: 2024-01-15 16:43:13.958988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82133fd39de9'
down_revision = '733f135d6fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curiosity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curiosity', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
