"""Added picture to facts

Revision ID: 899efd779747
Revises: 82133fd39de9
Create Date: 2024-01-15 16:44:50.541523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899efd779747'
down_revision = '82133fd39de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curiosity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curiosity', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
