"""Actualizare modele SQLAlchemy

Revision ID: c37254e08d07
Revises: f991918d08b3
Create Date: 2024-01-12 18:08:28.589882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37254e08d07'
down_revision = 'f991918d08b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('relationship', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('special_needs', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('adoption_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('terms', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('terms')
        batch_op.drop_column('adoption_reason')
        batch_op.drop_column('special_needs')
        batch_op.drop_column('relationship')
        batch_op.drop_column('activities')
        batch_op.drop_column('history')

    # ### end Alembic commands ###
