"""Added new rows

Revision ID: f991918d08b3
Revises: 27cb2aa669f2
Create Date: 2024-01-12 17:23:33.533474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f991918d08b3'
down_revision = '27cb2aa669f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('activities', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('relationship', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('special_needs', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('adoption_reason', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('terms', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('terms')
        batch_op.drop_column('adoption_reason')
        batch_op.drop_column('special_needs')
        batch_op.drop_column('relationship')
        batch_op.drop_column('activities')
        batch_op.drop_column('history')

    # ### end Alembic commands ###
